[_variables]
SUPABASE_URL = "https://qufhhvrvgbphlqskeyyj.supabase.co"
SUPABASE_SERVICE_ROLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1ZmhodnJ2Z2JwaGxxc2tleXlqIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc4NTA1NzM3OCwiZXhwIjoyMTAwNjMzMzc4fQ.1-_ecOLpmfr5vFn9H9AsBPk_iyFhAb6ANO2BXgO-xbg"
